myapp/urls.py
from django.urls import path
from myapp.views import *

app_name = "myapp"

urlpatterns = [
    path('home/',PostsPageView.as_view(),name='home'),
    path('login/',LoginPageView.as_view(),name='login'),
    path('logout/',LogoutPageView.as_view(),name='logout'),
    path('change/password/',PasswordChangePageView.as_view(),name='change_password'),
    path('accounts/profile/',ProfilePageView.as_view(),name='profile'),
    path('post/<int:pk>/',PostsDetailPageView.as_view(),name='post_details'),
    path('post/add/',PostsAddPageView.as_view(),name='post_add'),
    path('post/<int:pk>/edit',PostsUpdatePageView.as_view(),name='post_edit'),
    path('post/<int:pk>/delete',PostsDeletePageView.as_view(),name='post_delete'),
    path('reply/<str:title>',CommentReplyView.as_view(),name='reply_comment'),
    path('post-react/<int:pk>/',PostReactView.as_view(),name="post_react")

]

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('myapp.urls',namespace="myapp")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

myapp/models.py
from django.db import models
from django.urls import reverse

class Posts(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="post created at",null=True)
    class Meta:
        verbose_name_plural = "Our Posts"
    def __str__(self):
        return f"Post with title : {self.title}"
    
class Customers(models.Model):
    GENDER = (
        ("male","male"),
        ("female","female"),
    )
    name    = models.CharField(max_length = 200,verbose_name="customer name")
    age     = models.SmallIntegerField(default=18,verbose_name="customer age")
    image   = models.ImageField(upload_to = "customers/",verbose_name="customer profile")
    gender  = models.CharField(max_length = 200,choices= GENDER, default="male",verbose_name="customer gender")
    email   = models.EmailField(verbose_name="customer email")
    join_at = models.DateTimeField(auto_now_add=True,verbose_name="customer join at")

    #-----> meta
    class Meta:
        verbose_name_plural = "Our Customers"
    #-----> str
    def __str__(self):
        return f"user wiht full name : {self.name}"

class Comments(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    comment = models.TextField()
    
    def get_absolute_url(self):
        return reverse("post", kwargs={"pk": self.post.pk})
    
    class Meta:
        verbose_name_plural = "Comments"
    def __str__(self):
        return f"comment number ({self.id}) for post number ({self.post.id})"

class CommentsReply(models.Model):
    comment = models.ForeignKey(Comments, on_delete=models.CASCADE)
    reply = models.TextField()
    
    def get_absolute_url(self):
        return reverse("post", kwargs={"pk": self.post.pk})
    
    class Meta:
        verbose_name_plural = "Comments Reply"
    def __str__(self):
        return f"comment reply number ({self.id}) for comment with title ({self.comment.comment})"
    
class PostReact(models.Model):
    REACTS = ((str(i),str(i)) for i in ['LIKE','LOVE','SAD','CARE'])
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    post_react = models.CharField(max_length=10,choices=REACTS,default='LIKE')
    class Meta:
            verbose_name_plural = "Post React"
    def __str__(self):
        return f"Post number ({self.post.id}) has reacted with ({self.post_react})"

myapp/forms.py
from django import forms
from .models import *
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment']
        
    def __init__(self, *args, **kwargs):
        self.post = kwargs.pop('post')
        super().__init__(*args, **kwargs)
    
    def save(self, commit=True):
        comment = super().save(commit=False)
        comment.post = self.post
        if comment:
            comment.save()
        return comment

class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = CommentsReply
        fields = ['reply']

myapp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from myapp.models import Posts,Comments,CommentsReply,PostReact
from django.contrib.auth.views import LoginView,LogoutView,PasswordChangeView
from .forms import *

class LoginPageView(LoginView):
    template_name = "login.html"
    success_url = "/home/"

class ProfilePageView(TemplateView):
    template_name = 'profile.html'

class LogoutPageView(LogoutView):
    next_page = '/login/'
    
class PasswordChangePageView(PasswordChangeView):
    template_name = "password_change.html"
    success_url = "/login/"

class HomePageView(TemplateView):
    template_name = "home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Django Learning" 
        context["desc"] = "A paragraph generator is an AI-writing software that can take minimal text input and create an entire paragraph. With recent advances in natural language processing (NLP) and" 
        context["price"] = 100
        return context

class PostsPageView(ListView):
    model = Posts
    context_object_name = 'posts'
    template_name='home.html'
    
class PostReactView(View):
    def get(self, request, *args, **kwargs):
        post_id = self.kwargs['pk']
        react = request.GET.get('react')
        current_post = Posts.objects.get(id=post_id)
        if react == 'LIKE':
            PostReact.objects.create(post=current_post,post_react='LIKE')
        elif react == 'LOVE':
            PostReact.objects.create(post=current_post,post_react='LOVE')
        elif react == 'SAD':
            PostReact.objects.create(post=current_post,post_react='SAD')
        elif react == 'CARE':
            PostReact.objects.create(post=current_post,post_react='CARE')
        else:
            pass
        return redirect("/home/")
    
class PostsDetailPageView(DetailView):
    model = Posts
    # context_object_name = 'post'
    template_name='details.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_post = self.get_object()
        context["form"] = CommentForm(post = self.object)
        context['allcomment'] = Posts.objects.get(pk=current_post.pk)
        
        li,lo,sa,ca= 0,0,0,0
        for react in self.object.postreact_set.all():
            if react.post_react == 'LOVE':
                lo+=1
            elif react.post_react == 'LIKE':
                li+=1
            elif react.post_react == 'SAD':
                sa+=1
            else:
                ca+=1
        context['li'] = li
        context['lo'] = lo
        context['sa'] = sa
        context['ca'] = ca
        context['all_'] = lo+li+sa+ca
        return context

    def post(self, request,*args, **kwargs):
        post = self.get_object()
        form = CommentForm(request.POST,post=post)
        if form.is_valid():
            form.save()
            return redirect(f"/post/{post.pk}/")
        else:
            return self.render_to_response({'form':form,'post':post})
    
class PostsAddPageView(CreateView):
    model = Posts
    fields = ["title","content"]
    template_name='add.html'
    success_url = "/post/add/"
    
class PostsUpdatePageView(UpdateView):
    model = Posts
    template_name='update.html'
    fields = ["title","content"]
    success_url = "/"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = Posts.objects.get(id=self.kwargs['pk']) 
        return context
    
    
class PostsDeletePageView(DeleteView):
    model = Posts
    template_name='posts_confirm_delete.html'
    success_url = "/home/"

class CommentReplyView(CreateView):
    model = CommentsReply
    fields = ["reply"]
    template_name='reply.html'
    success_url = "/"
    
    def post(self, request,*args, **kwargs):
        comment = Comments.objects.get(comment=self.kwargs['title'])
        form = CommentReplyForm(request.POST)
        if form.is_valid():
            form.instance.comment = comment
            form.save()
            return redirect("/")
        else:
            return self.render_to_response({'form':form})

myapp/templates/add.html
<!doctype html>
{% load bootstrap5 %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/cba01bb0d0.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    
    <div class="container">
        <div class="row  pt-5">
            <div class="col-md-8 card p-5 mx-auto">
                <h2 class="text-center pb-2">
                    Add New Post
                </h2>
                <div class="row">
                    <div class="col-md-4 py-3">
                        <a href="{% url 'myapp:home' %}"><i class="fas fa-home text-dark"></i></a>
                    </div>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="col-md-12 btn btn-success">Add</button>
                </form>
            </div>
        </div>
        
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  </body>
</html>

myapp/templates/details.html
<h1>{{object.title}}</h1>
<p> ALL REACTS : {{all_}}</p>
<p>LIKE : {{li}}, LOVE : {{lo}}, CARE : {{ca}} , SAD : {{sa}} </p>
<hr>
<p>{{object.content}}</p>
<hr>
<p><a href= "{% url 'myapp:home'%}">Go Back</a></p>

<form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" id="myBtn" style="display:none;">Comment</button>
</form>

{% if allcomment.comments_set.all %}
    {% for comnt in allcomment.comments_set.all %}
        <p><strong>{{comnt.comment}}</strong></p>
        
        <a href="{% url 'myapp:reply_comment' comnt.comment %}">Add Reply</a>
        <br>
        ------------------
        {% for rep in comnt.commentsreply_set.all  %}
          <p><small>{{rep.reply}}</small></p>
        {% endfor %}
          
    {% endfor %}
{% else %}
<p>There is no comment yet !</p>
{% endif %}

<script>
    var input = document.getElementById("id_comment");
    input.addEventListener("keypress", function(event) {
      if (event.key === "Enter") {
        event.preventDefault();
        document.getElementById("myBtn").click();
      }
    });
</script>

myapp/templates/home.html
<!doctype html>
{% load bootstrap5 %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/cba01bb0d0.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    
    <div class="container">
        <div class="row  pt-5">
            <div class="col-md-10 card p-5 mx-auto">
                <h2 class="text-center pb-5 text-muted">
                    All Posts
                </h2>
                <div class="row">
                    <div class="col-md-4">
                        <a href="{% url 'myapp:post_add' %}" class=""><i class="fas fa-plus-circle" style="font-size: 30px;"></i></a>
                    </div>
                </div>
                {% for post in posts  %}
                <div class="row my-1 p-2" style="border:1px solid #333; border-radius: 25px;">
                   <div class="col-md-10">
                        <h5 class="text-dark"><a href="{% url 'myapp:post_details' post.id %}" style="text-decoration: none;color:#333;">( {{forloop.counter}} ) {{post.title}}</a></h5>
                        <div class="row">
                            <div class="col-md-6">
                                <p class="text-muted">Created at ({{post.created_at|timesince}} ago)</p>
                            </div>
                            <div class="col-md-3">
                                <p class="text-muted">All Comments ( {{post.comments_set.all.count}} )</p>
                                
                            </div>
                            <div class="col-md-3">
                                
                                <p class="text-muted">All Reacts ( {{post.postreact_set.all.count}} )</p>
                            </div>
                            
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row">
                                    <div class="col-md-6"><a href="{% url 'myapp:post_edit' post.id %}"><i class="fa fa-edit text-dark" aria-hidden="true"></i></a></div>
                                    <div class="col-md-6"><a href="{% url 'myapp:post_delete' post.id %}"><i class="fa fa-trash text-danger" aria-hidden="true"></i></a></div>
                                </div>
                            </div>
                        </div>
                   </div>
                   <div class="col-md-2">
                        <div class="row">
                            <div class="col-md-3"><a href="{% url 'myapp:post_react' post.id %}?react=LIKE"><i class="fas fa-thumbs-up"></i></a></div>
                            <div class="col-md-3"><a href="{% url 'myapp:post_react' post.id %}?react=LOVE"><i class="fas fa-heart text-danger"></i></a></div>
                            <div class="col-md-3"><a href="{% url 'myapp:post_react' post.id %}?react=SAD"> &#128557;</a></div>
                            <div class="col-md-3"><a href="{% url 'myapp:post_react' post.id %}?react=CARE">&#128525;</a></div>
                        </div>
                   </div>
                </div>
               {% endfor %}
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>
    

myapp/templates/login.html
<!doctype html>
{% load bootstrap5 %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    
    <div class="container">
        <div class="row  pt-5">
            <div class="col-md-8 card p-5 mx-auto">
                <h2 class="text-center pb-2">
                    Login
                </h2>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="col-md-12 btn btn-success">Login</button>
                </form>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  </body>
</html>

myapp/templates/password_change.html
<!doctype html>
{% load bootstrap5 %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        small{
            display:none;
        }
    </style>
  
  </head>
  <body>
    
    <div class="container">
        <div class="row  pt-5">
            <div class="col-md-8 card p-5 mx-auto">
                <h2 class="text-center pb-2">
                    Change Password
                </h2>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="col-md-12 btn btn-success">Save</button>
                </form>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  </body>
</html>

myapp/templates/posts_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <button type="button"><a href="{% url 'myapp:home' %}">Cancel</a></button>
</form>

myapp/templates/profile.html
<!doctype html>
{% load bootstrap5 %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    
    <div class="container">
        <div class="row  pt-5">
            <div class="col-md-8 card p-5 mx-auto">
                <h2 class="text-center pb-5 text-muted">
                    Personal Info
                </h2>
                <div class="row">
                    <div class="col-md-4"><strong>User Name : </strong></div>
                    <div class="col-md-8">{{request.user.username}}</div>
                </div>
                <div class="row">
                    <div class="col-md-4"><strong>Full Name : </strong></div>
                    <div class="col-md-8">{{request.user.first_name}}  {{request.user.last_name}}</div>
                </div>
                <div class="row">
                    <div class="col-md-4"><strong>Email Address : </strong></div>
                    <div class="col-md-8">{{request.user.email}}</div>
                </div>
                <div class="row">
                    <div class="col-md-4"><a href="{% url 'myapp:logout' %}" class="col-md-12 btn btn-danger mt-3">Logout</a></div>
                    <div class="col-md-4"><a href="{% url 'myapp:home' %}" class="col-md-12 btn btn-dark mt-3">Go Home</a></div>
                    <div class="col-md-4"><a href="{% url 'myapp:change_password' %}" class="col-md-12 btn btn-success mt-3">change password</a></div>
                </div>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  </body>
</html>

myapp/templates/reply.html
<form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Reply</button>
</form>

<h2><a href="{% url 'myapp:home' %}">Go Back</a></h2>
 

myapp/templates/update.html
<form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Update</button>
</form>